apiVersion: codeengine.cloud.ibm.com/v1beta1
kind: Application
metadata:
  name: vsi-viewer
spec:
  template:
    containers:
    - name: vsi-viewer
      image: <your-image-name>
      ports:
      - containerPort: 8080
      resources:
        requests:
          memory: "128Mi"
          cpu: "0.1"
        limits:
          memory: "256Mi"
          cpu: "0.2" 